// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import HelloController from "./hello_controller";
import CameraFormController from "./camera_form_controller";
import ScoreModeController from "./score_mode_controller.js";
application.register("hello", HelloController);
application.register("camera-form", CameraFormController);
application.register("score-mode", ScoreModeController);
